const ROW_WIDTH = 800;
const SPACE = 10;
const WIDTH_ITEM_GRID = 60;
const HEIGHT_ITEM_GRID = 50;

const WIDTH_ITEM_LIST = 40;
const HEIGHT_ITEM_LIST = 60;

export {
  ROW_WIDTH,
  SPACE,
  WIDTH_ITEM_GRID,
  HEIGHT_ITEM_GRID,
  WIDTH_ITEM_LIST,
  HEIGHT_ITEM_LIST,
};
